name: Build and Release Stable OpenSUSE Kernel with T2 Patches

on:
  push:
    tags: 'v*'  # Trigger on version tags (e.g., v6.6.21-t2)
  workflow_dispatch:
    inputs:
      version:
        description: 'Kernel version (e.g., 6.6.21)'
        required: true

env:
  ARCH: x86_64
  STABLE_BRANCH: stable
  RPM_BUILD_DIR: /home/runner/rpmbuild
  RPM_DIR: /home/runner/rpmbuild/RPMS/${{ env.ARCH }}
  SRPM_DIR: /home/runner/rpmbuild/SRPMS

jobs:
  build-release:
    runs-on: ubuntu-latest
    container:
      image: opensuse/tumbleweed:latest
      options: --privileged

    steps:
    - name: Determine version
      id: version
      run: |
        if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/v}" | cut -d'-' -f1 >> $GITHUB_OUTPUT
        fi
        echo "Using version: ${{ steps.version.outputs.VERSION }}"

    - name: Install dependencies
      run: |
        zypper --non-interactive refresh
        zypper --non-interactive install \
          git make gcc flex bison bc libopenssl-devel \
          ncurses-devel perl python3 rpm-build \
          patch cpio xz gzip rsync kmod hostname \
          elfutils libdw-devel libelf-devel dwarves

    - name: Clone OpenSUSE kernel (stable branch)
      run: |
        git clone --depth=1 --branch=${{ env.STABLE_BRANCH }} https://github.com/openSUSE/kernel.git
        cd kernel
        git submodule update --init --recursive

    - name: Checkout specific version if specified
      if: steps.version.outputs.VERSION != ''
      working-directory: ./kernel
      run: |
        git fetch --tags
        git checkout ${{ steps.version.outputs.VERSION }}

    - name: Clone T2 patches
      run: |
        git clone --depth=1 https://github.com/t2linux/linux-t2-patches.git

    - name: Apply patches
      working-directory: ./kernel
      run: |
        for patch in ../linux-t2-patches/*.patch; do
          patch -p1 < "$patch"
        done

    - name: Generate kernel configuration
      working-directory: ./kernel
      run: |
        # Generate default configuration
        make defconfig
        
        # Set local version suffix
        ./scripts/config --set-str CONFIG_LOCALVERSION "-t2"
        
        # Enable essential options needed for booting
        ./scripts/config --enable CONFIG_BLK_DEV_INITRD
        ./scripts/config --enable CONFIG_64BIT
        ./scripts/config --enable CONFIG_MODULES
        ./scripts/config --enable CONFIG_EFI_STUB
        ./scripts/config --enable CONFIG_EFI
        ./scripts/config --enable CONFIG_FB
        ./scripts/config --enable CONFIG_FRAMEBUFFER_CONSOLE
        
        # Finalize configuration
        make olddefconfig

    - name: Clean working tree while preserving config
      working-directory: ./kernel
      run: |
        # Preserve the .config file
        cp .config ../kernel.config
        
        # Clean the working tree
        git clean -fdx
        git reset --hard
        
        # Restore the config file
        mv ../kernel.config .config

    - name: Set up RPM build environment
      run: |
        # Create the full RPM build directory structure
        mkdir -p ${{ env.RPM_BUILD_DIR }}/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
        mkdir -p ${{ env.RPM_DIR }}  # Specifically create the arch directory
        mkdir -p ${{ env.SRPM_DIR }}
        echo "RPM build directories:"
        ls -la ${{ env.RPM_BUILD_DIR }}

    - name: Build kernel RPM packages
      working-directory: ./kernel
      run: |
        # Workaround for hostname issue
        export BUILD_HOST=github-runner
        
        # Build RPM packages
        make -j$(nproc) rpm-pkg
        
        # Verify RPMs were created
        echo "Built RPMs:"
        ls -la ${{ env.RPM_DIR }}
        echo "Built SRPMs:"
        ls -la ${{ env.SRPM_DIR }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-rpms
        path: |
          ${{ env.RPM_DIR }}/*.rpm
          ${{ env.SRPM_DIR }}/*.src.rpm

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.RPM_DIR }}/*.rpm
          ${{ env.SRPM_DIR }}/*.src.rpm
        generate_release_notes: true
